#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 26 09:58:00 2019
Weekly Problem 01: HIV Lab

@author: Lauren King
"""
import numpy as np

time=np.linspace(0,10,101)

B=0
A=10
alpha=7
beta=3.1

viral_load= A * np.exp(-alpha*time) + B * np.exp(-beta*time)
#print(viral_load)

plt.plot(time,viral_load)

data_file= "/Users/brightgreengirl/Documents/GitHub/PHYS-3211/Week 01/data/HIVseries.csv"
hiv_data=np.loadtxt(data_file, delimiter=",")
