#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  4 10:08:31 2019
Subtractive Cancellation- Harmonic Series

@author: Lauren King
"""
import numpy as np
import matplotlib.pyplot as plt


N=6
n=0
i=1
w=N
k=0
q=0
num1=float(0)
num2=float(0)
sum1=float(0)
sum2=float(0)
array1=np.arange(N+1)
array2=np.arange(N+1)


while i <= N:
    num1=1/i
    sum1+=num1
    array1[i]=sum1
    i+=1
    
    
while w >=1:
     num2= 1/w
     sum2+=num2
     array2[k]=sum2
     k+=1
     w-=1
     
print(sum1)     
print(sum2)

arraysum=np.arange(N+1)

arrayn=np.arange(N+1)

while q<N:
#    arraysum[q]=((array1[q])-(array2[q]))/((array1[q])+(array2[q]))
    q+=1
    
    
print(array1)
print(array2)
print(arrayn)
print(arraysum)
#plt.plot(arrayn,arraysum)    