#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 20 10:15:47 2019

Excercise 10

@author: Lauren King
"""
N=1000
circlex=np.zeros(N)
circley=np.zeros(N)
squarex=np.zeros(N)
squarey=np.zeros(N)
x=(rand.random(N))*2-1
y=(rand.random(N))*2-1
r=np.empty(N)
rval=0
pondsum=0


#print(squarex)
#print(squarey)
#print(circlex)
#print(circley)

i=0
a=0
b=0
while i<N:
    rval=np.sqrt((x[i]**2)+y[i]**2)
    r[i]=rval
    if rval<1:
        pondsum=pondsum+1
        circlex[a]=x[i]
        circley[a]=y[i]
        a=a+1
    else:
        squarex[b]=x[i]
        squarey[b]=y[i]
        #print(squarex)
        b=b+1
        pondsum=pondsum
    i=i+1    
        
        
pie=(pondsum*4)/N

#print(x)
#print(y)
#print(r)
#print(pondsum)  
print(pie)
#print(x)
#print(y)
#print(squarex)
#print(squarey)
#print(circlex)
#print(circley)
    
plt.scatter(squarex,squarey)
plt.scatter(circlex,circley)

        
    
plt.show  

#plt.scatter(x,y)
#plt.show

#circlex=np.zeros(N)
#circley=np.zeros(N)
#squarex=np.zeros(N)
#squarey=np.zeros(N)
#print(squarex)
#print(squarey)
#print(circlex)
#print(circley)